include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "build/**"
    - "lib/generated/**"
    - ".dart_tool/**"
  errors:
    unused_import: warning
    unused_local_variable: warning
    unnecessary_import: warning
    unnecessary_string_interpolations: warning
    unnecessary_brace_in_string_interps: warning
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_const_declarations: ignore
    dead_code: warning
    use_build_context_synchronously: ignore
    non_constant_identifier_names: warning
    unnecessary_dev_dependency: ignore

linter:
  rules:
    # 建议启用的规则
    - avoid_print
    - avoid_returning_null_for_void
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - empty_catches
    - empty_constructor_bodies
    - library_names
    - library_prefixes
    - no_duplicate_case_values
    - null_closures
    - prefer_conditional_assignment
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_statements
    - use_full_hex_values_for_flutter_colors
    - use_rethrow_when_possible
    - valid_regexps