name: glucocontrol
description: "Glucose Control App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  path: ^1.9.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: any
  riverpod_annotation: any
  drift: any
  sqlite3_flutter_libs: any
  sqflite_common_ffi: any
  sqlite3: any
  fl_chart: any
  webdav_client: any
  # flutter_blue_plus: any  # 未使用
  dio: any
  image_picker: any
  file_picker: any
  path_provider: any
  permission_handler: any
  # flutter_local_notifications: any  # 不需要系统通知
  # timezone: any  # 仅用于通知
  go_router: any
  freezed_annotation: any
  intl: any
  uuid: any
  shared_preferences: any

dev_dependencies:
  path: ^1.9.0
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
  drift_dev: any
  freezed: any
  flutter_launcher_icons: any

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app_icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
